/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type LogSubscriptionObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type LogSubscriptionParameters struct {

	// The id of directory.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/ds/v1beta1.Directory
	// +crossplane:generate:reference:extractor=github.com/upbound/upjet/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	DirectoryID *string `json:"directoryId,omitempty" tf:"directory_id,omitempty"`

	// Reference to a Directory in ds to populate directoryId.
	// +kubebuilder:validation:Optional
	DirectoryIDRef *v1.Reference `json:"directoryIdRef,omitempty" tf:"-"`

	// Selector for a Directory in ds to populate directoryId.
	// +kubebuilder:validation:Optional
	DirectoryIDSelector *v1.Selector `json:"directoryIdSelector,omitempty" tf:"-"`

	// Name of the cloudwatch log group to which the logs should be published. The log group should be already created and the directory service principal should be provided with required permission to create stream and publish logs. Changing this value would delete the current subscription and create a new one. A directory can only have one log subscription at a time.
	// +crossplane:generate:reference:type=github.com/upbound/provider-aws/apis/cloudwatchlogs/v1beta1.Group
	// +kubebuilder:validation:Optional
	LogGroupName *string `json:"logGroupName,omitempty" tf:"log_group_name,omitempty"`

	// Reference to a Group in cloudwatchlogs to populate logGroupName.
	// +kubebuilder:validation:Optional
	LogGroupNameRef *v1.Reference `json:"logGroupNameRef,omitempty" tf:"-"`

	// Selector for a Group in cloudwatchlogs to populate logGroupName.
	// +kubebuilder:validation:Optional
	LogGroupNameSelector *v1.Selector `json:"logGroupNameSelector,omitempty" tf:"-"`

	// Region is the region you'd like your resource to be created in.
	// +upjet:crd:field:TFTag=-
	// +kubebuilder:validation:Required
	Region *string `json:"region" tf:"-"`
}

// LogSubscriptionSpec defines the desired state of LogSubscription
type LogSubscriptionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LogSubscriptionParameters `json:"forProvider"`
}

// LogSubscriptionStatus defines the observed state of LogSubscription.
type LogSubscriptionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LogSubscriptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true

// LogSubscription is the Schema for the LogSubscriptions API. Provides a Log subscription for AWS Directory Service that pushes logs to cloudwatch.
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,aws}
type LogSubscription struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              LogSubscriptionSpec   `json:"spec"`
	Status            LogSubscriptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LogSubscriptionList contains a list of LogSubscriptions
type LogSubscriptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LogSubscription `json:"items"`
}

// Repository type metadata.
var (
	LogSubscription_Kind             = "LogSubscription"
	LogSubscription_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LogSubscription_Kind}.String()
	LogSubscription_KindAPIVersion   = LogSubscription_Kind + "." + CRDGroupVersion.String()
	LogSubscription_GroupVersionKind = CRDGroupVersion.WithKind(LogSubscription_Kind)
)

func init() {
	SchemeBuilder.Register(&LogSubscription{}, &LogSubscriptionList{})
}
